# Generated by Django 6.0.3 on 2026-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utente_id', models.IntegerField()),
                ('data_ordine', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(default='in_attesa', max_length=20)),
                ('totale', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantita', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordine_prodotto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.FloatField()),
                ('disponibile', models.IntegerField(blank=True, null=True)),
                ('immagine_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prodotto',
                'managed': False,
            },
        ),
    ]
