# Generated by Django 6.0.3 on 2026-04-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utente_id', models.IntegerField()),
                ('data_ordine', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(default='in_attesa', max_length=20)),
                ('totale', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordine',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.FloatField()),
                ('disponibile', models.IntegerField(blank=True, null=True)),
                ('immagine_url', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
            ],
            options={
                'db_table': 'prodotto',
            },
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantita', models.IntegerField(blank=True, null=True)),
                ('ordine', models.ForeignKey(db_column='ordine_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ordine')),
                ('prodotto', models.ForeignKey(db_column='prodotto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.prodotto')),
            ],
            options={
                'db_table': 'ordine_prodotto',
            },
        ),
    ]
