# Generated by Django 5.2.12 on 2026-04-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordine",
            options={"ordering": ["-data_ordine"]},
        ),
        migrations.AlterModelOptions(
            name="prodotto",
            options={"ordering": ["id"]},
        ),
    ]
