"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tiw9np40o40ov=t_wul_p3(cp09cymik=q*!wdd*kgyr*wvqoi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework", # Per django REST (DRF)
    'rest_framework_simplejwt', # Per JWT
    "django_filters", # Per fare i filtri dopo il ?
    "corsheaders", # Per CORS (Cross-Origin Resource Sharing). È una politica di sicurezza dei browser. Uso per altro client su un'altra porta, altrimenti il browser lo blocca.
    "api", # App REST del progetto
    "rest_framework_simplejwt.token_blacklist", # Per eseguire il logout.
]

MIDDLEWARE = [ # È una catena di "filtri" che ogni richiesta HTTP passa prima di arrivare alla view
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Da mettere prima di CommonMiddleware: Corsheaders è un middleware che aggiunge automaticamente gli header CORS alle risposte.
    'django.middleware.common.CommonMiddleware',
]

REST_FRAMEWORK = { # È la configurazione globale di DRF. Dice a tutte le tue API quale autenticazione usare (JWT), quali permessi di default (es. solo utenti autenticati) e formattazione JSON, paginazione, ecc... Senza, DRF non sa come gestire autenticazione/token.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Per browser come accesso (utile per test con admin)
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.AllowAny',  # Tutti possono accedere (per test)
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],

    # --- PAGINAZIONE ---
    # Classe built-in di DRF: numera le pagine con ?page=N
    'DEFAULT_PAGINATION_CLASS': 'config.settings.CustomPagination', # Funziona solo se la classe (in fondo) é nello stesso file. # Pre-built: rest_framework.pagination.PageNumberPagination.
    # Quanti oggetti per pagina di default (modificabile dal client con ?page_size=N).
    'PAGE_SIZE': 10,
}

from datetime import timedelta
SIMPLE_JWT = { # Configura come funzionano i token JWT. È il "motore" che genera/verifica i token Bearer.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Quanto dura il token principale (60 min).
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # Quanto dura il token di rinnovo (1 giorno).

    #Altri parametri per rotazione, algoritmi, ecc...
}

# Classe custom per permettere al client di modificare la page_size via query param.
# Senza questo, ?page_size=5 viene ignorato e si usa sempre PAGE_SIZE dal settings.
from rest_framework.pagination import PageNumberPagination

class CustomPagination(PageNumberPagination):
    page_size = 10  # Default: 10 elementi per pagina
    page_size_query_param = 'page_size' # Il client può usare ?page_size=5
    max_page_size = 100 # Limite massimo per evitare query troppo pesanti

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'gattini_cafe.db', # Db fornito
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
